


### 配置端口号
server:
  port: 8087
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

#rabbitmq:
#  host: 47.94.0.233
#  port: 5672
#  virtual-host: vhost-lemonplay
#  username: test
#  password: 123456
#  publisher-confirms: true #如果对异步消息需要回调必须设置为true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
        default-requeue-rejected: false
    virtual-host: /

