
server:
  port: 8083

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moli?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

