
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/moli?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: 12345678
        slave_1:
          driver-class-name: org.apache.hive.jdbc.HiveDriver
          url: jdbc:hive2://localhost:7001/ods
          username: hadoop
          password:

    # druid 配置信息
    druid:
      min-idle: 3
      max-active: 15
      initial-size: 5
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1

mybatis-plus:
  # 配置映射文件位置，classpath指resources
  mapper-locations: classpath*:mapper/*.xml # mapper.xml文件所在位置
  # 打印sql到控制台
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# pageHelper配置（官网推荐配置）
pagehelper:
  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式
  helperDialect: mysql
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  supportMethodsArguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql





