### 配置端口号
server:
  port: 8085

### 选择环境
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    # Redis数据源
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 86400000
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

mybatis-plus:
  # 配置映射文件位置，classpath指resources
  mapper-locations: classpath*:mapper/*.xml # mapper.xml文件所在位置
  # 打印sql到控制台
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

