
### 配置端口号
server:
  port: 8087

# mybatis
mybatis:
  typeAliasesPackage: cn.wjs.model
  mapper-locations: classpath*:mapper/**/*.xml # mapper.xml文件所在位置


#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

